name: chat
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs
  - archspec
  - asgiref
  - attrs
  - autobahn
  - automat
  - bcrypt
  - beautifulsoup4
  - boltons
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - certifi
  - cffi
  - channels
  - charset-normalizer
  - colorama
  - conda
  - conda-libmamba-solver
  - conda-package-handling
  - conda-package-streaming
  - constantly
  - cryptography
  - daphne
  - distro
  - django
  - django-cors-headers
  - djangorestframework
  - fmt
  - freetype
  - hyperlink
  - icu
  - idna
  - incremental
  - jsonpatch
  - jsonpointer
  - krb5
  - lcms2
  - lerc
  - libarchive
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libexpat
  - libffi
  - libiconv
  - libjpeg-turbo
  - libmamba
  - libmambapy
  - libnghttp2
  - libpng
  - libsolv
  - libsqlite
  - libssh2
  - libtiff
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - lz4-c
  - lzo
  - menuinst
  - ncurses
  - openjpeg
  - openssl
  - packaging
  - pillow
  - pip
  - platformdirs
  - pluggy
  - pthread-stubs
  - pyasn1
  - pyasn1-modules
  - pybind11-abi
  - pycosat
  - pycparser
  - pyopenssl
  - pysocks
  - pytesseract
  - python
  - python_abi
  - readline
  - reproc
  - reproc-cpp
  - requests
  - ruamel.yaml
  - ruamel.yaml.clib
  - service-identity
  - service_identity
  - setuptools
  - six
  - soupsieve
  - sqlparse
  - tk
  - tqdm
  - truststore
  - twisted
  - txaio
  - typing-extensions
  - typing_extensions
  - tzdata
  - urllib3
  - wheel
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - yaml-cpp
  - zope.interface
  - zstandard
  - zstd
